# Write your MySQL query statement below
SELECT DISTINCT L1.NUM AS CONSECUTIVENUMS
FROM LOGS L1
JOIN LOGS L2
  ON L2.ID = L1.ID +1
JOIN LOGS L3
  ON L3.ID = L1.ID +2
WHERE L1.NUM = L2.NUM
  AND L2.NUM = L3.NUM;    