# Write your MySQL query statement below
SELECT P.PRODUCT_ID, P.PRODUCT_NAME
FROM PRODUCT P
WHERE EXISTS (
    SELECT 1
    FROM SALES S
    WHERE S.PRODUCT_ID = P.PRODUCT_ID
      AND S.SALE_DATE BETWEEN '2019-01-01' AND '2019-03-31'

)
AND NOT EXISTS (
    SELECT 1
    FROM SALES S
    WHERE S.PRODUCT_ID = P.PRODUCT_ID
      AND (S.SALE_DATE < '2019-01-01'
            OR S.SALE_DATE > '2019-03-31')
);