# Write your MySQL query statement below
SELECT
  T.REQUEST_AT AS DAY,
  ROUND(
    SUM(CASE
        WHEN T.STATUS IN ('CANCELLED_BY_DRIVER','CANCELLED_BY_CLIENT')
        THEN 1
        ELSE 0     
  END) / COUNT(*),
  2
  ) AS 'CANCELLATION RATE'
FROM TRIPS T
JOIN USERS C
  ON T.CLIENT_ID = C.USERS_ID
JOIN USERS D
  ON T.DRIVER_ID = D.USERS_ID
WHERE
   C.BANNED = 'NO'
   AND D.BANNED = 'NO'
   AND T.REQUEST_AT BETWEEN '2013-10-01' AND '2013-10-03'
GROUP BY T.REQUEST_AT;