# Write your MySQL query statement below
SELECT
    ROUND(
        COUNT(DISTINCT A.PLAYER_ID) /
        (SELECT COUNT(DISTINCT PLAYER_ID) FROM ACTIVITY),
        2
    ) AS FRACTION
FROM ACTIVITY A
JOIN (
    SELECT
       PLAYER_ID,
       MIN(EVENT_DATE) AS FIRST_LOGIN
    FROM ACTIVITY
    GROUP BY PLAYER_ID
) F
   ON A.PLAYER_ID = F.PLAYER_ID
   AND A.EVENT_DATE = DATE_ADD(F.FIRST_LOGIN, INTERVAL 1 DAY);   