# Write your MySQL query statement below
SELECT 
DEPARTMENT,
EMPLOYEE,
SALARY
FROM (
    SELECT
     D.NAME AS DEPARTMENT,
     E.NAME AS EMPLOYEE,
     E.SALARY AS SALARY,
     DENSE_RANK() OVER (
        PARTITION BY E.DEPARTMENTID
        ORDER BY E.SALARY DESC
     ) AS RNK
    FROM EMPLOYEE E
    JOIN DEPARTMENT D
       ON E.DEPARTMENTID = D.ID
) AS RANKED
WHERE RNK <=3;