# Write your MySQL query statement below
SELECT 
  D.NAME AS DEPARTMENT,
  E.NAME AS EMPLOYEE,
  E.SALARY AS SALARY
FROM EMPLOYEE E
JOIN DEPARTMENT D
    ON E.DEPARTMENTID = D.ID
WHERE (E.DEPARTMENTID, E.SALARY) IN (
    SELECT DEPARTMENTID, MAX(SALARY)
    FROM EMPLOYEE
    GROUP BY DEPARTMENTID
);