SELECT ID, COUNT(*) AS NUM
FROM(
    SELECT REQUESTER_ID AS ID
    FROM REQUESTACCEPTED

    UNION ALL

    SELECT ACCEPTER_ID AS ID
    FROM REQUESTACCEPTED
) AS FRIENDS 
GROUP BY ID
ORDER BY NUM DESC
LIMIT 1;